[greenclip]
	blacklisted_applications = []
	enable_image_support = true
	history_file = "$XDG_CACHE_HOME/clip.history"
	image_cache_directory = "/tmp/clip-images"
	max_history_length = 50
	max_selection_size_bytes = 0
	static_history = []
	trim_space_from_selection = true
	use_primary_selection_as_input = false
